### ISSUE TITLE
Add support for 4GiB RAM board

### ISSUE THREAD

**Issue by deamen** [Doct2O/orangepi-zero3-bl#1]
Thanks for the excelent instruction.
I can compile u-boot v2023.10 with ATF v2.9.0, but the board hangs at "Trying to boot from MMC1"

> U-Boot SPL 2023.10-dirty (Nov 05 2023 - 00:43:46 +0000)
> DRAM: 4096 MiB
> Trying to boot from MMC1

**Comment by Doct2O** [comment]
> Thanks for the excelent instruction. I can compile u-boot v2023.10 with ATF v2.9.0, but the board hangs at "Trying to boot from MMC1"
> 
> > U-Boot SPL 2023.10-dirty (Nov 05 2023 - 00:43:46 +0000)
> > DRAM: 4096 MiB
> > Trying to boot from MMC1

Thanks for your feedback. Sure, I can take a look at that, but first I need to get my hands on the 4GiB variant (only got couple of 1GiB, since it was cheap as dirt). Stay tuned.
Btw. Have you tried to use the prebuild images from repo, same outcome?

**Comment by deamen** [comment]
> Btw. Have you tried to use the prebuild images from repo, same outcome?

Thanks for pointing me to the correct direction.
I confirm you patch works on the 4GiB board.
I was building u-boot with the incorrect bl31 binary, I was using bl31.elf but your instruction says bl31.bin.

I can boot Fedora 39 Beta on Orange Pi Zero3 now.
